Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/04/2023
Var
num, mult, i:inteiro

Inicio

mult <- 1
Repita
escreval ("Escreva 5 numeros do tipo inteiro: ")
leia (num)
mult <- mult*num
i<- i+1

ate i>=5

ESCREVAL("resultado da multiplicacao: ", mult)


Fimalgoritmo