Algoritmo "Tipo de dado"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Tipo de caracter: Patricia")
Escreval("Tipo de inteiro: ", 11)
Escreval("Tipo de real: ", 1.50)
Escreval("Tipo de booleano: ", verdadeiro)


Fimalgoritmo